# Starter golangci-lint configuration for lugatuic/goberus
run:
  tests: true
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - unused
    - typecheck
    - gosimple
  disable:
    - gochecknoglobals
    - gochecknoinits

issues:
  exclude-use-default: false
  exclude:
    - "Error return value is not checked.*(Close|Write|Flush).*\\n"
    - "should have comment or be unexported"

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lugatuic/goberus
